config/routes.rb
Rails.application.routes.draw do
  resources :client_shares
  resources :visits, only: [:create, :index]
  resources :transactions, only: [:index]
  resources :accounts, only: [:show]
  devise_for :clients, controllers: { sessions: 'clients/sessions', registrations: 'clients/registrations' }, skip: [:registrations]

  devise_scope :client do
    root to: "clients/sessions#new"
    post '/account_register' => 'clients/registrations#create'
    get "/open_account" => "clients/registrations#new", as: "new_account_registration"
  end
  
   

  get '/my_account' => 'accounts#show_account'
  get '/account_list' => 'accounts#index'
  get '/my_transactions' => 'accounts#my_transactions'
  get '/account_transaction/:id' => 'accounts#account_transactions', as: 'account_transactions'
  get '/became_vip/:id' => 'accounts#became_vip', as: 'set_account_vip'
  get '/remove_vip/:id' => 'accounts#remove_vip', as: 'remove_account_vip'

  get '/deposit' => 'transactions#deposit'
  post '/execute_deposit' => 'transactions#execute_deposit'

  get '/withdraw' => 'transactions#withdraw'
  post '/execute_withdraw' => 'transactions#execute_withdraw'

  get '/transfer' => 'transactions#transfer'
  post '/execute_transfer' => 'transactions#execute_transfer'

  get '/shares' => 'shares#index'
  get '/my_shares' => 'shares#my_shares'
  post '/buy_shares' => 'shares#buy_shares'
  post '/sell_shares' => 'shares#sell_shares'

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :client
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :authenticate_client!
  before_action :client_only!, only: [:create]
  before_action :vip_only!, only: [:create]
  before_action :authenticate_manager!, only: [:index]
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    AccountActionsService.new(current_client,nil).request_visit
    redirect_to my_account_path, notice: 'Solicitação de visita enviada'

  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:client_id)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.slim
= form_for @visit do |f|
  - if @visit.errors.any?
    #error_explanation
      h2 = "#{pluralize(@visit.errors.count, "error")} prohibited this visit from being saved:"
      ul
        - @visit.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :client
    = f.text_field :client
  .actions = f.submit

app/views/visits/edit.html.slim
h1 Editing visit

== render 'form'

= link_to 'Show', @visit
'  |
= link_to 'Back', visits_path

app/views/visits/index.html.slim
.container.center.col
  .card
    h3 Visitas
    table.highlight.bordered
      thead
        tr
          th Cliente
          th Data

      tbody
        - @visits.each do |visit|
          tr
            td = visit.client.name
            td = visit.created_at.strftime('%d/%m/%Y %H:%M')

br

app/views/visits/new.html.slim
h1 New visit

== render 'form'

= link_to 'Back', visits_path

app/views/visits/show.html.slim
p#notice = notice

p
  strong Client:
  = @visit.client

= link_to 'Edit', edit_visit_path(@visit)
'  |
= link_to 'Back', visits_path