config/routes.rb
Rails.application.routes.draw do
  resources :client_shares
  resources :visits, only: [:create, :index]
  resources :transactions, only: [:index]
  resources :accounts, only: [:show]
  devise_for :clients, controllers: { sessions: 'clients/sessions', registrations: 'clients/registrations' }, skip: [:registrations]

  devise_scope :client do
    root to: "clients/sessions#new"
    post '/account_register' => 'clients/registrations#create'
    get "/open_account" => "clients/registrations#new", as: "new_account_registration"
  end
  
   

  get '/my_account' => 'accounts#show_account'
  get '/account_list' => 'accounts#index'
  get '/my_transactions' => 'accounts#my_transactions'
  get '/account_transaction/:id' => 'accounts#account_transactions', as: 'account_transactions'
  get '/became_vip/:id' => 'accounts#became_vip', as: 'set_account_vip'
  get '/remove_vip/:id' => 'accounts#remove_vip', as: 'remove_account_vip'

  get '/deposit' => 'transactions#deposit'
  post '/execute_deposit' => 'transactions#execute_deposit'

  get '/withdraw' => 'transactions#withdraw'
  post '/execute_withdraw' => 'transactions#execute_withdraw'

  get '/transfer' => 'transactions#transfer'
  post '/execute_transfer' => 'transactions#execute_transfer'

  get '/shares' => 'shares#index'
  get '/my_shares' => 'shares#my_shares'
  post '/buy_shares' => 'shares#buy_shares'
  post '/sell_shares' => 'shares#sell_shares'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_client!
  before_action :set_client_account, only: [:deposit, :withdraw, :transfer]
  before_action :client_only!

  before_action :build_transaction, only: [:deposit, :withdraw, :transfer]
  before_action :permit_transaction, only: [:execute_deposit, :execute_withdraw, :execute_transfer]
  # GET /transactions
  
  def deposit
    @is_transfer = false
    @action_name = 'Depósito'
    @account_action = execute_deposit_path
    render :account_action
  end

  def execute_deposit
    AccountActionsService.new(current_client,params[:transaction]).deposit!  
    redirect_to my_account_path, notice: 'Deposito efetuado!'
  end

  def withdraw
    @is_transfer = false
    @action_name = 'Retirada'
    @account_action = execute_withdraw_path
    render :account_action
  end

  def execute_withdraw      
    AccountActionsService.new(current_client,params[:transaction]).withdraw    
    redirect_to withdraw_path, notice:  current_client.account.errors.first[1]  and return if current_client.account.errors.any?
    redirect_to my_account_path, notcie: 'Retirada efetuada!' 
  end

  def transfer
    @is_transfer = true
    @action_name = 'Transferência'
    @account_action = execute_transfer_path
    render :account_action
  end

  def execute_transfer         
    redirect_to transfer_path, notice:  AccountActionsService.new(current_client,params[:transaction]).transfer    
  end

  private
    
    def permit_transaction
      params.require(:transaction).permit(:value,:description,:target_account)
    end

    def build_transaction
      @transaction = Transaction.new
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.slim
= form_for @transaction, url: @account_action do |f|
  - if @transaction.errors.any?
    #error_explanation
      h2 = "#{pluralize(@transaction.errors.count, "error")} prohibited this transaction from being saved:"
      ul
        - @transaction.errors.full_messages.each do |message|
          li = message

  .field
    = f.label 'Valor'
    = f.text_field :value, data: { role: 'money',  a_dec: '.' }
  .field
    = f.label 'Descrição'
    = f.text_field :description, maxlength: 32
  - if is_transfer
    .field
      = f.label 'Conta Destino'
      = f.text_field :target_account, maxlength: 5, onkeypress:'return isNumber(event)'
  .actions = f.submit 'Concluído', class: 'btn'

javascript:
  $(function() {
    var money_fields;
    money_fields = $('input[data-role=money]');
    money_fields.autoNumeric('init');
    return money_fields.keydown(function(event) {
      if (event.keyCode === 13) {
        return $(this).autoNumeric('set', $(this).autoNumeric('get'));
      }
    });
  });

app/views/transactions/account_action.html.slim
.container.center.col
    .card
        h4
            = "Saldo:#{number_to_currency( @account.balance,unit:'R$')}"
        br
        p
            = notice
        h4       
            = @action_name
        br
            = render 'transactions/form', is_transfer: @is_transfer

app/views/transactions/edit.html.slim
h1 Editing transaction

== render 'form'

= link_to 'Show', @transaction
'  |
= link_to 'Back', transactions_path

app/views/transactions/index.html.slim
h1 Listing transactions

table
  thead
    tr
      th Value
      th Account
      th Description
      th
      th
      th

  tbody
    - @transactions.each do |transaction|
      tr
        td = transaction.value
        td = transaction.account
        td = transaction.description
        td = link_to 'Show', transaction
        td = link_to 'Edit', edit_transaction_path(transaction)
        td = link_to 'Destroy', transaction, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Transaction', new_transaction_path

app/views/transactions/new.html.slim
h1 New transaction

== render 'form'

= link_to 'Back', transactions_path

app/views/transactions/show.html.slim
p#notice = notice

p
  strong Value:
  = @transaction.value
p
  strong Account:
  = @transaction.account
p
  strong Description:
  = @transaction.description

= link_to 'Edit', edit_transaction_path(@transaction)
'  |
= link_to 'Back', transactions_path