config/routes.rb
Rails.application.routes.draw do
  resources :client_shares
  resources :visits, only: [:create, :index]
  resources :transactions, only: [:index]
  resources :accounts, only: [:show]
  devise_for :clients, controllers: { sessions: 'clients/sessions', registrations: 'clients/registrations' }, skip: [:registrations]

  devise_scope :client do
    root to: "clients/sessions#new"
    post '/account_register' => 'clients/registrations#create'
    get "/open_account" => "clients/registrations#new", as: "new_account_registration"
  end
  
   

  get '/my_account' => 'accounts#show_account'
  get '/account_list' => 'accounts#index'
  get '/my_transactions' => 'accounts#my_transactions'
  get '/account_transaction/:id' => 'accounts#account_transactions', as: 'account_transactions'
  get '/became_vip/:id' => 'accounts#became_vip', as: 'set_account_vip'
  get '/remove_vip/:id' => 'accounts#remove_vip', as: 'remove_account_vip'

  get '/deposit' => 'transactions#deposit'
  post '/execute_deposit' => 'transactions#execute_deposit'

  get '/withdraw' => 'transactions#withdraw'
  post '/execute_withdraw' => 'transactions#execute_withdraw'

  get '/transfer' => 'transactions#transfer'
  post '/execute_transfer' => 'transactions#execute_transfer'

  get '/shares' => 'shares#index'
  get '/my_shares' => 'shares#my_shares'
  post '/buy_shares' => 'shares#buy_shares'
  post '/sell_shares' => 'shares#sell_shares'

end

app/views/layouts/_nav_items.html.slim
- if current_client.is_manager?
    li
        = link_to 'Contas', account_list_path
    li
        = link_to 'Visitas Agendadas', visits_path        
    li
        = link_to 'Ações', shares_path
-else
    li
        = link_to 'Saldo', my_account_path
    li
        = link_to 'Extrato', my_transactions_path
    li
        = link_to 'Depósito', deposit_path
    li
        = link_to 'Retirada', withdraw_path
    li
        = link_to 'Transferências', transfer_path
    li
        = link_to 'Ações', shares_path
    li
        = link_to 'Minhas Ações', my_shares_path
    - if current_client.vip 
        li
            = link_to 'Agendar Visita', visits_path,  method: :post, data: { confirm: 'Gostaria de agendar uma visita?' }
li 
    = link_to('Sair', destroy_client_session_path, class: 'btn', method: :delete, data: { confirm: 'Sair, Tem certeza?' })  

app/views/layouts/_navbar.html.slim
nav
  .nav-wrapper
    .brand-logo 
        = current_client.present? ? "Ola #{current_client.name}" : 'NilBank, Um banco que não existe!' 
    - if current_client.present?
      ul#nav-mobile.right.hide-on-med-and-down
        = render 'layouts/nav_items'
      

app/views/layouts/_transactions.html.slim
table.bordered.highlight
    thead
    tr
        th Data
        th Valor
        th Descrição
        th Conta
        //th
        //th

    tbody
        - transactions.each do |t|
            tr
            td = t.created_at.strftime('%d/%m/%Y %H:%M')
            td class="#{t.value >= 0 ? 'black-text' : 'red-text'}"
                = t.value >= 0 ? number_to_currency(t.value, :unit => "R$") : "(#{number_to_currency(t.value, :unit => "R$")})"
            td = t.description
            td = t.target_account

        //td = link_to 'Destroy', account, data: { confirm: 'Are you sure?' }, method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    title Nilbank
    
    = javascript_include_tag 'application'
    = csrf_meta_tags
    /! Compiled and minified CSS
    link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css" rel="stylesheet" /
    /! Compiled and minified JavaScript
    script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/js/materialize.min.js" 
    = stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons'
    = stylesheet_link_tag    'application', media: 'all'

  body
    = render 'layouts/navbar'
    = yield