config/routes.rb
Rails.application.routes.draw do
  resources :client_shares
  resources :visits, only: [:create, :index]
  resources :transactions, only: [:index]
  resources :accounts, only: [:show]
  devise_for :clients, controllers: { sessions: 'clients/sessions', registrations: 'clients/registrations' }, skip: [:registrations]

  devise_scope :client do
    root to: "clients/sessions#new"
    post '/account_register' => 'clients/registrations#create'
    get "/open_account" => "clients/registrations#new", as: "new_account_registration"
  end
  
   

  get '/my_account' => 'accounts#show_account'
  get '/account_list' => 'accounts#index'
  get '/my_transactions' => 'accounts#my_transactions'
  get '/account_transaction/:id' => 'accounts#account_transactions', as: 'account_transactions'
  get '/became_vip/:id' => 'accounts#became_vip', as: 'set_account_vip'
  get '/remove_vip/:id' => 'accounts#remove_vip', as: 'remove_account_vip'

  get '/deposit' => 'transactions#deposit'
  post '/execute_deposit' => 'transactions#execute_deposit'

  get '/withdraw' => 'transactions#withdraw'
  post '/execute_withdraw' => 'transactions#execute_withdraw'

  get '/transfer' => 'transactions#transfer'
  post '/execute_transfer' => 'transactions#execute_transfer'

  get '/shares' => 'shares#index'
  get '/my_shares' => 'shares#my_shares'
  post '/buy_shares' => 'shares#buy_shares'
  post '/sell_shares' => 'shares#sell_shares'

end

app/models/account.rb
class Account < ActiveRecord::Base

  attr_accessor :transaction_desc, :target_account
  belongs_to :client
  has_many :transactions, -> {order 'created_at DESC'}
  
  validates :balance,numericality: {greater_than_or_equal_to: 0, message:'Saldo Insuficiente'}, on: :update, unless: Proc.new {self.client.vip}
  
  after_update :generate_transaction
  before_update :interest_date, if: Proc.new { |a| self.balance_was >= 0 }

  private
  def generate_transaction
    value = self.balance - self.balance_was
    return if value==0
    Transaction.create(value: value, account_id: self.id, description: transaction_desc, target_account: target_account)
  end

  def interest_date
    last_request = Time.now
  end


end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_client!
  before_action :authenticate_manager!, only: [:index,:show,:account_transactions, :became_vip, :remove_vip]
  before_action :set_account, only: [:show, :account_transactions, :became_vip, :remove_vip]
  
  before_action :client_only!, only: [:show_account,:my_transactions]
  before_action :set_client_account, only: [:show_account, :my_transactions]
  before_action :load_transactions, only: [:my_transactions, :account_transactions]
  before_action :load_last_transactions, only: [:show, :show_account] 


  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  def show_account
    
    render :show
  end

  def my_transactions
    render :transactions
  end

  def account_transactions
    render :transactions
  end

  def became_vip
    @account.client.vip = true
    @account.client.save
    redirect_to account_list_path
  end

  def remove_vip
    @account.client.vip = false
    @account.client.save
    redirect_to account_list_path
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
  end

    def load_transactions
      @transactions = @account.transactions
    end

    def load_last_transactions
      @transactions = @account.transactions.first(3)
    end

    
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:balance)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.slim
= form_for @account do |f|
  - if @account.errors.any?
    #error_explanation
      h2 = "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      ul
        - @account.errors.full_messages.each do |message|
          li = message

  .field
    = f.label 'balance'
    = f.text_field :balance
  .field
    = f.label :client
    = f.text_field :client
  .actions = f.submit

app/views/accounts/index.html.slim
.container.center.col
  .card
    h3 Contas
    = link_to 'Abrir Conta', new_account_registration_path, class: 'btn'
    br
    table.bordered.highlight
      thead
        tr
          th Numero
          th Cliente
          th VIP
          th
      
      tbody
        - @accounts.each do |account|
          tr
            td = account.client.account_number
            td = account.client.name
            td = account.client.vip ? 'Sim' : 'Não' 
            td style='{display=inline-block;}'
              = link_to 'Extrato', account_transactions_path(account), class:'btn'
              = ' ' 
              = link_to 'Exibir', account_path(account), class:'btn'
              = ' ' 
              - if !account.client.vip
                = link_to 'Tornar VIP', set_account_vip_path(account), class:'btn'
              - else
                = link_to 'Retirar VIP', remove_account_vip_path(account), class:'btn'
      
    br

app/views/accounts/new.html.slim
h1 New account

== render 'form'

= link_to 'Back', accounts_path

app/views/accounts/show.html.slim
.container.center.col
  .card
    h5
    h4
      = "Conta #{@account.client.account_number} #{@account.client.vip ? 'VIP' : '' }"
    p
      strong Cliente:
      = @account.client.name
    p
      h5
        strong 
          = 'Saldo'
          div class="#{@account.balance >= 0 ? 'black-text' : 'red-text'}"
            = number_to_currency(@account.balance, :unit => "R$") 
    br
    p
     = notice
    br
    p 
      strong Ultimas Transações:
      = render 'layouts/transactions', transactions: @transactions
      
    - if current_client.is_manager?
      = link_to 'Voltar', account_list_path, class:'btn'
    br

app/views/accounts/transactions.html.slim
.container.center.col
  .card
    h4
      = "Extrato de #{@account.client.account_number}"
    p
      = render 'layouts/transactions', transactions: @transactions